variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

pages:
  stage: deploy
  script:
  - bundle install
  - bundle exec jekyll build -d public --trace
  artifacts:
    paths:
    - public
  tags:
    - osx