
#
# Jekyll basic configurations
#
source:         
destination:    _site
timezone:       Australia/Brisbane
permalink:      /:title.html
markdown:       kramdown
highlighter:    rouge
include:        ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/


# basic settings
title: "Keiran Lovett"
email: "kvclovett@gmail.com"
description: "AAA Game Production. Building teams and making games."
author: "Keiran"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://keiranlovett.com" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%d %B %Y"

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

author:
  twitter: keiranlovett
  name: Keiran
  url: https://keiranlovett.com/

# paginations & permalinks
paginate: 20
paginate_path: "_pages/writings/page:num/"
permalink: pretty

# Used by Safari mask-icon, Chrome Web App theme color
colors:
  theme:        "#ff00b4"
  background:   "#fff"

# Google Analytics tracking code
google_analytics:
  enabled:      false
  id:           UA-xxxxxxx
  url:          https://www.google-analytics.com/analytics.js

# Site Twitter account handle
twitter:        keiranlovett

# Twitter Cards large images
#
# Use summary card with large image for Twitter Cards, require theme support
#
# Default:      true
tc_large_image: true

# Force UTF-8 encoding
#
# Enable this will simply add <meta charset="utf-8"> to the head of your pages
#
# Default:      true
force_utf_8:    true

# collections
collections:
  - works
  - resume
  - talks

# archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Build settings
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-picture-tag-ng
  - jekyll-postfiles

picture_tag_ng:
  backend: imagemagick
  parallel: false
  threads: 16
  background_color: FFFFFF
picture_versions:
    s:
      out_size: 400
    m:
      out_size: 700
      media: 1200
    l:
      out_size: 1200
    xl:
      out_size: 2000
      default: true
sass:
  style: compressed
