# Sections content configuration file
## 
### use navigation.yml file to re-order, delete or add section of each card
### here you can find all content in all pre-build sections

### About [ about ]
about:
  title: "About Me"
  image: "assets/images/profile.jpg"
  text: "
        <p>
          <strong>G'day! I’m Keiran Lovett.</strong><br>Based in Canada, and working in Game Production at Ubisoft. Over the last decade I've shipped games and projects across various roles (producer, game designer, developer).
        </p>
        "
#  list:
#    - label: "Name"
#      value: "24"
#    - label: "Age"
#      value: "22 Years"
#    - label: "Job"
#      value: "Web Developer"
#    - label: "Citizenship"
#      value: "Keiran"
#    - label: "Residence"
#      value: "Kiev"
#    - label: "E-mail"
#      value: "johndoe@domain.com"

  download:
    text: "Download CV"
    link: "assets/files/keiranlovett_cv_2023.pdf"

  social:
    - title: "Twitter"
      icon: "social-twitter"
      url: "https://twitter.com/keiranlovett"
    - title: "GitHub"
      icon: "social-github"
      url: "https://github.com/keiranlovett"
    - title: "Linkedin"
      icon: "social-linkedin"
      url: "https://hk.linkedin.com/in/keiranlovett"

### Showreel [ showreel ]
showreel:
  title: "Showreel"
  youtube_id: "we9rnDoJdKM"

### Resume [ resume ]
resume:
  experience:
    title: "Experience"
    items:
      - year: "02/2022 - present"
        name: "Production Manager, Ubisoft Winnipeg"
        text: "Building teams for announced and unannounced Ubisoft projects. Point person for Ubisoft studios partnerships."
        
      - year: "12/2018 - 12/2021"
        name: "Senior Product Manager, Shadow Factory"
        text: "Managing the design and development of industry-leading clients (Facebook, Apple, PGM, and more...)."

      - year: "11/2017 - 12/2018"
        name: "Technical Director, Shadow Factory"
        text: "Developing technical architecture of various studio projects. Setting up studio pipelines."

      - year: "06/2016 - 10/2017"
        name: "Game Developer, Lan Kwai Fong Group"
        text: "Research / Development of new technologyin AR, VR, and mobile platforms. (Unity, Unreal Engine)."

      - year: "06/2014 - 03/2016"
        name: "User Interface Designer, Insight Robotics"
        text: "Designing and developing tools for robotics powered, early-warning fire detection system and software."
        
      - year: "11/2012 - 05/2014"
        name: "Game Designer, Frenzoo Limited"
        text: "Developer of 'MeGirl' IOS / Android mobile games series."

  education:
    title: "Highlights"
    items:
      - year: "2020"
        name: "Today At Apple"
        text: "I gave a 1hr talk on the history and technology behind augmented reality. Included [interactive coding session on iPad ](https://github.com/ShadowFactory/TodayAtApple-SwiftPlaygroundsAR) "

      - year: "2019"
        name: "Big Indie Pitch - Judge"
        text: "I was a judicator for the finalist of [Big Indie Pitch](https://www.bigindiepitch.com) for Pocket Game Connects."

      - year: "2019"
        name: "Game Developers Conference"
        text: "Participating in GDC show floor to showcase the VR game Stupid Cupid."

      - year: "2018"
        name: "Roundtable F8"
        text: "I joined a closed-door roundtable with Facebook Leadership to share my thoughts the future of Augmented Reality with Mark Zuckerberg 1:1"


### Skills [ skills ]
skills:
  columns:
    - type: "default" #skills progress type - default, dotted, circles, list
      title: "Design Skills"
      items:
        - label: "Web Design"
          value: "70" #0-100 progress in %

        - label: "Illustrations"
          value: "90" #0-100 progress in %

        - label: "Photoshop"
          value: "75" #0-100 progress in %

        - label: "Graphic Design"
          value: "80" #0-100 progress in %

    - type: "dotted" #skills progress type - default, dotted, circles, list
      title: "Languages Skills"
      items:
        - label: "English"
          value: "90" #0-100 progress in %

        - label: "German"
          value: "70" #0-100 progress in %

        - label: "Italian"
          value: "55" #0-100 progress in %

        - label: "French"
          value: "85" #0-100 progress in %

    - type: "circles" #skills progress type - default, dotted, circles, list
      title: "Coding Skills"
      items:
        - label: "WordPress"
          value: "95" #0-100 progress in %

        - label: "PHP / MYSQL"
          value: "75" #0-100 progress in %

        - label: "Angular / JavaScript"
          value: "85" #0-100 progress in %

        - label: "HTML / CSS"
          value: "90" #0-100 progress in %

    - type: "list" #skills progress type - default, dotted, circles, list
      title: "Knowledge"
      items:
        - label: "Website hosting"
          value: "" #0-100 progress in %

        - label: "iOS and android apps"
          value: "" #0-100 progress in %

        - label: "Create logo design"
          value: "" #0-100 progress in %

        - label: "Design for print"
          value: "" #0-100 progress in %

        - label: "Modern and mobile-ready"
          value: "" #0-100 progress in %

        - label: "Advertising services include"
          value: "" #0-100 progress in %

        - label: "Graphics and animations"
          value: "" #0-100 progress in %

        - label: "Search engine marketing"
          value: "" #0-100 progress in %

### Services [ services ]
services:
  title: "My Services"
  items:
    - icon: "social-html5"
      name: "Front-end"
      text: "Front-end web development is the practice of converting data to a graphical interface, through the use of HTML, CSS, and JavaScript."

    - icon: "ipad"
      name: "Mobile Application"
      text: "A mobile application, most commonly referred to as an app, is a type of application software designed to run on a mobile."

    - icon: "ios-search-strong"
      name: "Investigation"
      text: "Investigation, examination, inquiry, research express the idea of an active effort to find out something."

    - icon: "code"
      name: "Programming"
      text: "Computer programming is the process of designing and building an executable computer program to accomplish a specific."

    - icon: "help-buoy"
      name: "Awesome Supports"
      text: "Awesome Support is the most versatile and feature-rich. Get started for free and add premium features as your business grows."

    - icon: "social-chrome"
      name: "Web Development"
      text: "Web development is the work involved in developing a Web site for the Internet or an intranet and social network services."

### Clients [ clients ]
clients:
  title: "Clients"
  items:
    - url: "https://www.google.com"
      image: "assets/img/clients/client_1.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_2.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_3.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_1.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_2.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_3.png"

### Contact Info [ contacts-info ]
contacts_info:
  title: "Get in Touch"
  list:
    - label: "Email"
      icon:  "email"
      value: "Recruiter reaching out about roles? Student looking for advice or a free protfolio review? Or you simply want to chat? Feel free to email me!</a>"

#    - label: "Address"
#      icon: "ios-location"
#      value: "2621 W Pico Blvd, Los Angeles"

### Contact Form [ contacts-form ]
contacts_form:
  title: "Contact Form"

