### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  dark_ui: 1 # activated dark ui styles
  dark_mode_toggle: 1
  rtl: 0 # activated rtl styles
  navbar: 0 # for disable sidebar and sidebar button change to 0
  preload: 0
  preloader: "loading..." # preloader loading text
  dynamic_background: "background.jpg"
  work_show_all: 0
  work_highlight_limit: 6