name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install imagemagick and libvips
        run: sudo apt-get update && sudo apt-get install imagemagick
      - name: Jekyll Action (only on main branch)
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        #if: github.ref == 'refs/heads/main'