    name: Jekyll build and deploy

    on:
      push:
        branches:
          - main # Or your default branch

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup Ruby
            uses: ruby/setup-ruby@v1
            with:
              ruby-version: '3.x' # Specify your desired Ruby version
              bundler-cache: true # Installs dependencies from Gemfile.lock

          - name: Build Jekyll site
            run: bundle exec jekyll build

          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./_site
